import AppForm from '../app-components/Form/AppForm';

Vue.component('user-form', {
    mixins: [AppForm],
    data: function() {
        return {
            form: {
                about:  '' ,
                amazon:  '' ,
                auto_balance:  false ,
                balance:  '' ,
                balance_visibility:  '' ,
                birth_date:  '' ,
                blocked_countries:  '' ,
                body_type:  '' ,
                city:  '' ,
                country:  '' ,
                country_visibility:  false ,
                cover:  '' ,
                email:  '' ,
                email_verified_at:  '' ,
                ethnicity:  '' ,
                eye_color:  '' ,
                facebook:  '' ,
                fancentro:  '' ,
                gender:  '' ,
                hair_color:  '' ,
                instagram:  '' ,
                interested_in:  '' ,
                interface_lang:  '' ,
                kyc_approved_at:  '' ,
                languages:  '' ,
                model_birth:  '' ,
                model_city:  '' ,
                model_country:  '' ,
                model_firstname:  '' ,
                model_lastname:  '' ,
                mylang_visibility:  false ,
                name:  '' ,
                notify_news:  false ,
                notify_offers:  false ,
                partner:  '' ,
                password:  '' ,
                photo:  '' ,
                rating_private:  '' ,
                rating_public:  '' ,
                snapchat:  '' ,
                specifics:  '' ,
                studio:  '' ,
                subculture:  '' ,
                subscription:  '' ,
                subscription_expire_at:  '' ,
                subscription_renewal:  '' ,
                twitter:  '' ,
                type:  '' ,
                username:  '' ,
                visibility:  '' ,
                xhamster:  '' ,

            }
        }
    },

});
